# Generated by Django 5.2.4 on 2026-05-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateTimeField()),
                ('fecha_egreso', models.DateTimeField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('nombre_paciente', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=50)),
                ('servicio', models.CharField(blank=True, default='', max_length=100)),
                ('quien_reporta', models.CharField(blank=True, default='', max_length=100)),
                ('destino', models.CharField(blank=True, default='', max_length=100)),
                ('procedimiento', models.CharField(blank=True, default='', max_length=255)),
                ('medico', models.CharField(blank=True, default='', max_length=100)),
                ('aux_enfermeria', models.CharField(blank=True, default='', max_length=100)),
                ('conductor', models.CharField(blank=True, default='', max_length=100)),
                ('radio_operador', models.CharField(blank=True, default='', max_length=100)),
                ('ambulancia', models.CharField(blank=True, default='', max_length=100)),
                ('observacion', models.TextField(blank=True, default='')),
                ('mes', models.IntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Traslado',
                'verbose_name_plural': 'Traslados',
                'db_table': 'cruetraslados_traslado',
                'ordering': ['-fecha_reporte'],
                'indexes': [models.Index(fields=['mes'], name='cruetraslad_mes_c6df24_idx'), models.Index(fields=['fecha_reporte'], name='cruetraslad_fecha_r_08d68c_idx')],
            },
        ),
    ]
