# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trasladopaciente',
            name='aux_enfermeria',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
